[package]
name = "plasmid-core"
version = "0.1.0"
edition = "2024"

[dependencies]
plasmid-fs = { workspace = true }

thiserror = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true